// 🗄️ COMPLETE EXHAUSTIVE ESL TUTOR GUIDANCE DATABASE
const FOCUS_GUIDANCE = {
  errors: {
    articles: [
      'Use gap-fill tasks with real sentences from today’s lesson, then move into short speaking tasks where the student chooses articles in real time.',
      'Take sentences the student said incorrectly and get them to notice and correct article mistakes themselves.',
      'Run a quick correction drill: say sentences aloud and have the student fix article errors instantly.',
      'Use a picture description task where the student must choose a, an, or the naturally while speaking.',
      'Highlight patterns from today and get the student to rebuild sentences with correct articles.',
      'Pause after an article error and repeat the sentence with rising intonation to prompt self-correction.',
      'Write the student’s incorrect sentence and remove only the article, asking them to supply it.',
      'Contrast two versions (with and without article) and ask which sounds more natural and why.',
      'Ask the student to justify their article choice out loud to build conscious control.',
      'Use minimal pairs (I saw dog / I saw a dog / I saw the dog) and discuss meaning differences.',
      'Reformulate the student’s sentence correctly and ask them to repeat with emphasis on the article.',
      'Collect 3–4 errors and run a delayed correction slot focused only on article choice.',
      'Ask the student to slow down and insert a micro-pause before nouns to force article decisions.',
      'Use a dictation from their own errors, requiring accurate article reconstruction.',
      'Turn their sentence into a question so they must reprocess the article in a new structure.',
      'Highlight a pattern (e.g. missing \'the\') and challenge them to notice it in their own speech.',
      'Ask them to repeat the same sentence in a different context to test article flexibility.',
      'Use a quick-fire drill: teacher says noun → student must produce full noun phrase with article.',
      'Give two options (a/the) and force instant choice without overthinking.',
      'Ask them to exaggerate the article slightly in speech to increase awareness.',
      'Recycle one corrected sentence multiple times across the lesson until it sticks.',
      'Use a picture and ask them to introduce objects (a/an) vs refer back (the).',
      'Interrupt gently at the error and get immediate repair before continuing.',
      'Ask the student to compare L1 vs English usage briefly to highlight difference.',
      'Turn errors into a running “target” and remind them mid-task.',
      'Ask them to identify their own most common article mistake at the end of the task.',
      'Use a substitution drill swapping nouns but keeping correct article patterns.',
      'Get them to correct a deliberately wrong sentence you produce.',
      'Ask for repetition only when the article is correct — no correction, just expectation.',
      'Build a short narrative and require consistent article tracking throughout.',
      'Ask them to explain why “the” is needed in a specific sentence.',
      'Use boardwork to visually group article types (general vs specific reference).',
      'Remove all articles from a short text and ask them to restore them.',
      'Force slower speech for one minute focusing only on noun phrases.',
      'Ask them to upgrade nouns (dog → the big dog) with correct article use.',
      'Use a memory task where correct article use affects meaning recall.',
      'Ask them to spot article errors in a short transcript of their own speech.',
      'Recycle the same noun across different contexts to shift article use.',
      'Challenge them to produce three correct sentences in a row without prompting.',
      'Use a timed task where accuracy matters more than fluency.',
      'Ask them to reformulate their own incorrect sentence immediately.',
      'Provide a model sentence and require exact repetition including article.',
      'Use a correction code (e.g. “A?”) to prompt self-repair instead of explaining.',
      'Build a dialogue where article accuracy is required to continue.',
      'Ask them to choose between zero article vs article and explain.',
      'Use real objects in the room to anchor article meaning.',
      'Delay correction, then revisit errors as a focused mini-lesson.',
      'Ask them to record themselves and notice article omissions.',
      'Focus on one article type only (e.g. “the”) for 2 minutes of intensive practice.',
      'Challenge them to maintain accuracy under slight time pressure.',
      'Ask them to summarise using correct article use in each sentence.',
      'Use a chain activity where each sentence must include a correct noun phrase.',
      'Interrupt only for article errors to increase salience.',
      'Ask them to predict article use before speaking.',
      'Get them to teach you the rule they just applied.',
      'Finish with a reflection: “What article mistake did you fix today?”'
    ],
    tense: [
      'Pick the most frequent tense slip and correct it consistently; a short visual timeline helps.',
      'Have the student retell a story changing it from present to past tense dynamically.',
      'Run a 2-minute error correction game focusing entirely on the misplaced tenses from today.',
      'Pause and repeat the incorrect verb phrase with rising intonation to trigger self-correction.',
      'Ask the student to retell the same sentence in a different time frame.',
      'Put their sentence on a simple timeline and ask them to justify the tense choice.',
      'Reformulate the sentence correctly and ask for exact repetition.',
      'Ask \'when exactly?\' after each sentence to force tense clarification.',
      'Contrast two tenses (I go / I went) and ask which matches their meaning.',
      'Interrupt and require immediate correction before continuing.',
      'Ask them to narrate the same event in past, then present.',
      'Collect 3 tense errors and run a focused correction slot.',
      'Use a quick-fire drill: teacher gives time cue, student produces sentence.',
      'Ask them to slow down and think before verb production.',
      'Highlight repeated misuse and label it as today\'s target.',
      'Ask them to correct your deliberately wrong tense.',
      'Use substitution drills changing only the time reference.',
      'Require repetition until tense is correct — no explanation.',
      'Ask them to explain why they chose that tense.',
      'Turn their sentence into a question to reprocess the verb.',
      'Ask for a follow-up sentence using the same tense correctly.',
      'Build a short story maintaining consistent tense.',
      'Ask them to spot tense errors in a short transcript.',
      'Force a contrast: \'What’s different between these two sentences?\'',
      'Use a time adverb (yesterday, now) and require matching tense.',
      'Ask them to summarise using consistent tense.',
      'Interrupt only for tense errors for 2 minutes.',
      'Ask them to reformulate immediately after correction.',
      'Use a dictation based on their own errors.',
      'Challenge them to produce 3 correct tense sentences in a row.',
      'Ask them to describe a routine vs a past event.',
      'Use real-life questions requiring specific tense use.',
      'Require full sentence answers, not fragments.',
      'Ask them to predict tense before speaking.',
      'Use a visual timeline and place events.',
      'Ask them to retell a story with different tense framing.',
      'Delay correction and revisit as a mini-lesson.',
      'Use controlled prompts (If…, When…) to trigger tense.',
      'Ask them to compare L1 tense usage briefly.',
      'Force repetition with corrected form only.',
      'Build a dialogue requiring tense shifts.',
      'Ask for a narrative using at least 3 correct verb forms.',
      'Highlight one tense and focus exclusively for 2 minutes.',
      'Ask them to identify their own tense mistake.',
      'Use a transformation task (present → past).',
      'Ask them to justify meaning differences between tenses.',
      'Require slower speech to improve accuracy.',
      'Ask for examples using the same tense pattern.',
      'Use a correction code like \'T?\' for self-repair.',
      'Build a chain story maintaining tense consistency.',
      'Ask them to correct written versions of their speech.',
      'Focus on irregular verbs from today.',
      'Ask them to retell using time markers.',
      'End with reflection: \'What tense did you fix today?\' '
    ],
    word_order: [
      'Sentence-scramble cards work well here — let the student rebuild the structure themselves, then compare it aloud to a model sentence.',
      'Write a scrambled sentence on the board and have them race to fix the structure out loud.',
      'Practice building sentences backwards starting from the object to highlight structural dependencies.',
      'Write the sentence incorrectly and ask them to rebuild it aloud.',
      'Use a sentence scramble and require fast reconstruction.',
      'Ask them to compare correct vs incorrect versions.',
      'Reformulate and ask for exact repetition.',
      'Interrupt and prompt immediate reordering.',
      'Ask them to slow down and build sentence step-by-step.',
      'Use a pattern frame (Subject + Verb + Object).',
      'Ask them to explain why the order is wrong.',
      'Build sentences backwards from the object.',
      'Use substitution drills maintaining structure.',
      'Ask them to correct your incorrect sentence.',
      'Highlight today\'s recurring pattern.',
      'Ask for repetition only when correct.',
      'Use a dictation with incorrect order to fix.',
      'Build a chain where each sentence follows structure.',
      'Ask them to identify word order errors in text.',
      'Use visual blocks (S/V/O) to rearrange.',
      'Ask them to reformulate immediately.',
      'Force shorter sentences for control.',
      'Ask for a second version of same sentence.',
      'Use transformation tasks (question form).',
      'Ask them to predict structure before speaking.',
      'Use contrast pairs to highlight meaning.',
      'Focus on adverb placement.',
      'Ask them to repeat corrected sentence twice.',
      'Build a dialogue requiring correct order.',
      'Interrupt only for word order errors.',
      'Ask them to summarise with correct structure.',
      'Use guided sentence starters.',
      'Require full sentence responses.',
      'Ask them to self-identify errors.',
      'Use timed drills for structure.',
      'Build a narrative with consistent order.',
      'Ask for variation with same structure.',
      'Use correction codes like \'WO?\'.',
      'Ask them to reconstruct from memory.',
      'Use L1 comparison briefly.',
      'Focus on one structure intensely.',
      'Ask them to explain structure rule.',
      'Use a board to map sentence parts.',
      'Ask them to reorder spoken sentence.',
      'Require repetition until correct.',
      'Use minimal pairs with order difference.',
      'Ask them to fix written sentences.',
      'Use question formation tasks.',
      'Highlight pattern and revisit.',
      'Build controlled speaking tasks.',
      'Ask for multiple correct examples.',
      'Use chain corrections.',
      'Ask them to reflect on error pattern.',
      'End with: \'What structure did you fix today?\''
    ],
    pronunciation: [
      'Choose two or three sounds to work on and stick with them — minimal pairs followed by a short recording the student can listen back to makes the improvement tangible.',
      'Isolate the specific sound patterns that tripped them up today and run a brief shadowing exercise.',
      'Use exaggerated mouth modeling for the problem sounds, then have the student track their own rhythm over three sentences.',
      'Isolate the target sound and drill it briefly.',
      'Contrast minimal pairs (ship/sheep).',
      'Ask for repetition with exaggerated clarity.',
      'Record and play back for self-noticing.',
      'Break word into syllables and rebuild.',
      'Model and require exact repetition.',
      'Ask them to slow down speech.',
      'Highlight one sound for 2 minutes.',
      'Use sentence-level repetition.',
      'Ask them to identify incorrect sound.',
      'Use mouth positioning explanation briefly.',
      'Contrast correct vs incorrect versions.',
      'Use rhythm tapping for stress.',
      'Ask them to exaggerate stress patterns.',
      'Drill word stress in phrases.',
      'Build short sentences using target sound.',
      'Interrupt and correct immediately.',
      'Ask for self-correction after model.',
      'Use shadowing technique.',
      'Focus on connected speech patterns.',
      'Ask them to repeat 3 times correctly.',
      'Use chunking instead of word-by-word.',
      'Ask them to identify stress errors.',
      'Use intonation drills.',
      'Build a short dialogue with target sounds.',
      'Ask for slow, clear repetition.',
      'Use visual phonetic cues if needed.',
      'Contrast stressed vs unstressed forms.',
      'Focus on endings (e.g. -ed).',
      'Ask them to repeat in different sentences.',
      'Use echo correction.',
      'Ask them to mark stress in writing.',
      'Use call-and-response drills.',
      'Focus on clarity over speed.',
      'Ask them to notice their own errors.',
      'Use repetition in context.',
      'Build fluency with controlled accuracy.',
      'Ask for consistent improvement across attempts.',
      'Use real-life phrases.',
      'Focus on sentence rhythm.',
      'Ask them to mimic model speech.',
      'Use correction only on key errors.',
      'Ask them to compare recordings.',
      'Use guided reading aloud.',
      'Focus on natural speech flow.',
      'Ask for repetition with emotion/intonation.',
      'Build short presentations.',
      'Use targeted drilling then free speaking.',
      'Ask them to maintain accuracy in conversation.',
      'Highlight improvement explicitly.',
      'End with: \'What sound did you improve today?\''
    ],
    vocabulary: [
      'Revisit today\'s target words at the start of next session, then push them into natural conversation rather than drilling in isolation.',
      'Set up a quick taboo-style game where the student has to define today\'s new words without saying them.',
      'Have the student substitute basic verbs from today\'s notes with more advanced alternatives in a short speaking drill.',
      'Reformulate the student’s sentence with a better word and ask them to repeat it exactly.',
      'Give two alternatives and ask which fits the meaning better and why.',
      'Ask the student to explain what they meant to say, then refine the word choice together.',
      'Write the sentence and underline the incorrect word, prompting self-correction.',
      'Ask for a more precise version of the same sentence.',
      'Provide a near-synonym and ask them to compare nuance.',
      'Build a short dialogue forcing reuse of the corrected word.',
      'Ask them to replace a vague word (thing, stuff) with something specific.',
      'Use a quick-fire drill: give situations, student chooses best word.',
      'Ask them to paraphrase the sentence using different vocabulary.',
      'Highlight overused words and challenge them to avoid them.',
      'Ask them to upgrade simple words into more natural alternatives.',
      'Give a sentence and ask them to improve it.',
      'Use collocation matching (make/do/take) in context.',
      'Ask them to identify incorrect word choice in a model sentence.',
      'Contrast two incorrect vs correct collocations.',
      'Ask for 3 variations of the same sentence with different wording.',
      'Use substitution drills focusing on correct word use.',
      'Ask them to justify why a word is correct.',
      'Build a mini-task requiring repeated use of target vocabulary.',
      'Interrupt and correct only word choice errors for 2 minutes.',
      'Ask them to reformulate immediately after correction.',
      'Use a picture and require precise vocabulary.',
      'Ask for a more natural version of their sentence.',
      'Replace one word and ask them to rebuild the sentence.',
      'Use a synonym ladder (basic → precise).',
      'Ask them to notice repeated incorrect choices.',
      'Provide feedback using reformulation, not explanation.',
      'Ask them to choose between formal/informal options.',
      'Use real-life scenarios requiring specific vocabulary.',
      'Ask them to summarise using improved word choice.',
      'Focus on one lexical set (e.g. travel verbs).',
      'Ask them to avoid translation and think in English meaning.',
      'Give a phrase and ask them to complete it naturally.',
      'Ask them to correct your wrong word choice.',
      'Build a chain where each sentence must improve vocabulary.',
      'Use gap-fill with multiple correct options and discuss nuance.',
      'Ask them to repeat corrected version twice.',
      'Use a correction code like \'WW?\' to prompt self-repair.',
      'Ask for a more specific verb instead of a general one.',
      'Highlight and recycle corrected vocabulary later in the lesson.',
      'Ask them to describe the same idea more naturally.',
      'Use comparison tasks (good vs better phrasing).',
      'Ask them to predict better vocabulary before speaking.',
      'Require use of target word in next answer.',
      'Use a mini-presentation with improved vocabulary.',
      'Ask them to expand a sentence using richer vocabulary.',
      'Challenge them to avoid repeating the same word twice.',
      'Ask them to reflect on one improved word choice.',
      'Use delayed correction focused on vocabulary.',
      'Ask them to teach you the better word they learned.',
      'End with: \'What word did you improve today?\''
    ],
    fluency: [
      'Remove the pressure to be perfect: timed free-talk tasks with familiar topics help the student build momentum and trust their own instincts.',
      'Try a "speed-dating" style fluency sprint: give them 60 seconds to summarize an idea, then repeat it in 45 seconds, then 30.',
      'Run a low-stakes discussion where pausing is banned but hesitation devices like "let me think" or "that\'s an interesting point" are explicitly tracked and rewarded.',
      'Set a 30-second speaking task where stopping is not allowed.',
      'Ask the student to repeat the same answer but more smoothly.',
      'Use a timed task with familiar content to reduce cognitive load.',
      'Allow planning time, then require continuous speaking.',
      'Ask them to speak again without stopping after correction.',
      'Model a smooth version and ask them to imitate.',
      'Use chunking: give them phrases to reduce hesitation.',
      'Ask them to continue speaking even if unsure.',
      'Use a ‘no silence’ rule for 1 minute.',
      'Ask them to restart the sentence more fluently.',
      'Focus on rhythm rather than accuracy for one task.',
      'Encourage use of fillers (well, so, actually) to maintain flow.',
      'Repeat the same question to build fluency.',
      'Use a familiar topic to reduce hesitation pressure.',
      'Ask them to speak faster deliberately.',
      'Use a storytelling task with continuous flow.',
      'Interrupt pauses and prompt continuation.',
      'Ask them to paraphrase instead of stopping.',
      'Use guided prompts to keep them moving.',
      'Build confidence with short, fast answers.',
      'Ask for longer answers without interruption.',
      'Use a chain speaking activity.',
      'Ask them to describe without stopping for 20 seconds.',
      'Repeat the same task aiming for smoother delivery.',
      'Use a ‘keep talking’ signal during pauses.',
      'Ask them to avoid translating mentally.',
      'Encourage risk-taking over perfection.',
      'Use repetition to build automaticity.',
      'Ask them to continue even after mistakes.',
      'Use a countdown to push continuous speech.',
      'Build fluency through predictable structures.',
      'Ask them to connect ideas using simple linkers.',
      'Use shadowing to improve flow.',
      'Focus on speaking in chunks, not words.',
      'Ask them to expand answers without stopping.',
      'Use a picture description with continuous speech.',
      'Encourage them to talk through uncertainty.',
      'Ask for faster second attempts.',
      'Use role-play to maintain flow.',
      'Ask them to speak without planning mid-task.',
      'Reduce correction to maintain fluency.',
      'Ask them to keep going even if imperfect.',
      'Use prompts to extend answers.',
      'Build automatic responses with repetition.',
      'Ask them to speak for a fixed time.',
      'Use conversational drills.',
      'Encourage smoother delivery over accuracy.',
      'Ask them to avoid long pauses consciously.',
      'Repeat task focusing only on fluency.',
      'Ask them to reflect on hesitation moments.',
      'Reinforce improvement in flow explicitly.',
      'End with: \'Did that feel smoother this time?\''
    ],
    expression: [
      'Ask the student to say the same idea in a simpler way.',
      'Prompt them with a sentence starter to support expression.',
      'Reformulate their idea and ask them to repeat it.',
      'Ask guiding questions to help build the idea step-by-step.',
      'Encourage them to use simpler language instead of stopping.',
      'Provide key vocabulary and ask them to rebuild the idea.',
      'Ask them to describe the idea using examples.',
      'Break the idea into smaller parts and rebuild.',
      'Ask them to try again after hearing a model.',
      'Use a scaffolded structure (I think… because…).',
      'Encourage paraphrasing instead of stopping.',
      'Ask them to explain the idea differently.',
      'Provide options and let them choose.',
      'Use visuals or context to support meaning.',
      'Ask follow-up questions to extend the idea.',
      'Encourage risk-taking over accuracy.',
      'Ask them to use basic language first, then upgrade.',
      'Build the idea collaboratively with prompts.',
      'Ask them to repeat after reformulation.',
      'Use guided speaking frames.',
      'Ask them to describe a similar situation.',
      'Encourage them to keep talking through difficulty.',
      'Ask them to expand one sentence into two.',
      'Use substitution to build complexity.',
      'Ask them to clarify meaning with examples.',
      'Provide missing words and rebuild sentence.',
      'Ask them to summarise their idea simply.',
      'Use role-play to support expression.',
      'Ask them to explain the idea to a beginner.',
      'Encourage use of known language only.',
      'Ask them to restructure the sentence.',
      'Provide partial sentence and ask them to complete.',
      'Ask them to describe instead of translate.',
      'Use repetition to refine expression.',
      'Ask them to build the idea gradually.',
      'Encourage using gestures + words together.',
      'Ask them to restate the idea clearly.',
      'Use prompts to guide structure.',
      'Ask them to connect ideas logically.',
      'Provide feedback through reformulation.',
      'Ask them to expand on one point.',
      'Encourage them to speak even if imperfect.',
      'Ask them to try again more clearly.',
      'Use scaffolding then remove support.',
      'Ask them to compare two ideas.',
      'Encourage clearer structure in answers.',
      'Ask them to organise ideas before speaking.',
      'Use guided questions to build response.',
      'Ask them to reflect on what was difficult.',
      'Reinforce successful expression attempts.',
      'Build confidence through repetition.',
      'End with: \'Can you say that more clearly now?\''
    ]
  },
  positives: {
    good_grammar: [
      'The foundation is solid — now\'s a good time to introduce more demanding structures like conditionals or passive forms to keep progress moving.',
      'Challenge them to upgrade their solid structures by weaving in inversion or past modals during the next discussion.',
      'They have the basics down perfectly; push them to use complex embedded clauses to express nuances in their opinions next time.'
    ],
    good_vocab: [
      'Good word choices are already there; push for more precision by exploring synonyms and collocations, and highlight moments when the student picks the best word, not just a safe one.',
      'Encourage them to anchor these great words by grouping them into topical collocations during next week\'s speaking tasks.',
      'Actively push them away from safe descriptive words into more idiomatic or precise domain-specific language next session.'
    ],
    complex_structure: [
      'Build on this by introducing relative clauses or concession phrases — model a few examples and invite the student to create their own in a short speaking activity.',
      'Challenge them to maintain this structural complexity even during fast-paced, unpredictable conversational topics.',
      'Have them experiment with combining two simple thoughts into a single elegant, complex sentence using subordinating conjunctions.'
    ],
    connector: [
      'Widen the range: practise less common linkers like "as a result", "despite", or "not only…but also" through a quick write-then-speak activity.',
      'Challenge them to connect three completely unrelated ideas using advanced transition words.',
      'Have them speak for one minute while forcing them to use at least three different connectors.'
    ],
    natural_phrase: [
      'Keep feeding in authentic input — real conversations and role-play tasks help fixed phrases become automatic rather than something the student has to think about.',
      'Take the natural expressions they used today and challenge them to deploy them in a completely different conversational context next time.',
      'Introduce the structural variations of those exact phrases to help turn casual idioms into versatile active vocabulary.'
    ]
  }
};

// Bind to window context so it functions instantly as a global resource
window.FOCUS_GUIDANCE = FOCUS_GUIDANCE;